spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  cloud:
    function:
      definition: hinataScheduleNotificationFunction
  profiles:
    active: dev
line.bot:
  handler.path: /callback
