spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  cloud:
    function:
      definition: hinataScheduleNotificationFunction
    gcp:
      datastore:
        emulator:
          enabled: true