#!/usr/bin/env just --justfile

set dotenv-load := true

deployment_name := "sakamichi-infra"
config_file_path := "deployment_manager/sakamichi_infra_config.yml"

# create Deployment Manager deployment
create-deployment:
  gcloud deployment-manager deployments create {{deployment_name}} \
    --config {{config_file_path}} \
    --project {{env_var("PROJECT_ID")}}

# update Deployment Manager deployment
update-deployment:
  gcloud deployment-manager deployments update {{deployment_name}} \
    --config {{config_file_path}} \
    --project {{env_var("PROJECT_ID")}}
