apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    cloud.googleapis.com/location: asia-northeast1
  name: sakamichi-scraper
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 80
      containers:
        - image: asia-northeast1-docker.pkg.dev/sakamichi-noticer/sakamichi-docker-repo/sakamichi-scraper:latest
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
      serviceAccountName: sakamichi-scraper-executor@sakamichi-noticer.iam.gserviceaccount.com
      timeoutSeconds: 300
