apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sakamichi-scraper
spec:
  template:
    spec:
      serviceAccountName: sakamichi-scraper-executor@sakamichi-noticer.iam.gserviceaccount.com
      containers:
        - image: asia-northeast1-docker.pkg.dev/sakamichi-noticer/sakamichi-docker-repo/sakamichi-scraper:latest
