name: deploy-sakamichi-scraper

on: workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPOSITORY: sakamichi-docker-repo
  IMAGE: sakamichi-scraper
  TAG: latest
  REGION: asia-northeast1
  HOSTNAME_LIST: asia-northeast1-docker.pkg.dev

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker auth
        run: echo "Y" | gcloud auth configure-docker ${{ env.HOSTNAME_LIST }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./sakamichi_scraper
          push: true
          tags: ${{ env.HOSTNAME_LIST }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          metadata: sakamichi_scraper/service.yml
          region: ${{ env.REGION }}
