name: deploy-sakamichi-scraper

on: workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker auth
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./sakamichi_scraper
          push: true
          tags: asia-northeast1-docker.pkg.dev/sakamichi-noticer/sakamichi-docker-repo/sakamichi-scraper
