name: deploy-hinata-schedule-notifier

on: workflow_dispatch

concurrency: deploy-hinata-schedule-notifier

jobs:
  deploy-hinata-schedule-notifier:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: temurin
          cache: maven

      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.CI_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.CI_EXECUTOR_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build Function
        run: ./mvnw package
        working-directory: sakamichi_noticer/hinata-schedule-notifier/

      - name: Deploy Function
        run: scripts/deploy.sh
        working-directory: sakamichi_noticer/hinata-schedule-notifier/
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
