name: deploy-hinata-schedule-notifier

on: workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SPRING_PROFILES_ACTIVE: prod

jobs:
  deploy-hinata-schedule-notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('sakamichi_noticer/hinata-schedule-notifier/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Function
        run: ./mvnw package
        working-directory: sakamichi_noticer/hinata-schedule-notifier/

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Function
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: hinata-schedule-notifier
          runtime: java11
          region: asia-northeast1
          entry_point: org.springframework.cloud.function.adapter.gcp.GcfJarLauncher
          event_trigger_resource: gs://hinata-schedule
          event_trigger_type: google.storage.object.finalize
          source_dir: sakamichi_noticer/hinata-schedule-notifier/target/deploy
          memory_mb: 512
          service_account_email: hinata-notifier-executor@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      # - name: Deploy Function
      #   run: |
      #     gcloud functions deploy hinata-schedule-notifier \
      #       --runtime java11 \
      #       --region asia-northeast1 \
      #       --entry-point org.springframework.cloud.function.adapter.gcp.GcfJarLauncher \
      #       --trigger-resource gs://hinata-schedule \
      #       --trigger-event google.storage.object.finalize \
      #       --source sakamichi_noticer/hinata-schedule-notifier/target/deploy \
      #       --memory 512MB \
      #       --service-account hinata-notifier-executor@sakamichi-noticer.iam.gserviceaccount.com
